
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YWMwZmZlZjE0MGVmMWQ1ZTllOWY5NCIsImVtYWlsIjoiYmlsaXN1bWFlcmVzc28yQGdtYWlsLmNvbSIsInJvbGUiOjIsImlhdCI6MTc1Njk4Mzc1NywiZXhwIjoxNzU3NTg4NTU3fQ.sFkGE4gGD-egNJ7suFKxYWcx8Ynm1V7-z-A2DBED6FU

###
POST http://localhost:8000/api/v1/category
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "cat 2"
}
###
GET http://localhost:8000/api/v1/category
Authorization: Bearer {{token}}